# Site settings
# title:
# email:
# description: > # this means to ignore newlines until "baseurl:"
# baseurl: "students-test/" # the subpath of your site, e.g. /blog/
# url: "" # the base hostname & protocol for your site

twitter_username: yourname
github_username: Kaboomfisch
title: I.BA_222_GENCG.H2001
subtitle: I.BA_222_GENCG.H2001

# # Build settings
# markdown: kramdown

collections:
  01-Sketches:
    output: true
